kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bigdisk-nfs 
spec:
  storageClassName: "drobo-iscsi-nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Ti
